### ISSUE TITLE
missing colours?

### ISSUE THREAD

**Issue by Joep-DDQ** [burggraaff/water-colour#1]
On the file statistics.py it requests 

from . import colours

any idea where I can find these?

**Comment by burggraaff** [comment]
Hi Joep,

Do you get an import error when running this? Because it should be coming from [the \_\_init\_\_.py file in this repository.](https://github.com/burggraaff/smartphone-water-colour/blob/c6f6ed858801340065915e8b1579cc8b53c63335/wk/__init__.py#L1) That in turn draws it from [the pyspectacle library](https://github.com/monocle-h2020/camera_calibration) - have you installed that? `pip install pyspectacle` should work.

**Comment by Joep-DDQ** [comment]
Yes I have that library. I got the import to work now. Still many other issues though related to calibration files to figure out.
